### ISSUE TITLE
how to perform around face with disguise accessoseries

### ISSUE THREAD

**Issue by adoniyas** [isarandi/synthetic-occlusion#2]
Hello very good repo. if u have any suggessions on how to perform face synthetic occlusions wtih mask, sun glass, scarfes etc.

**Comment by isarandi** [comment]
You would need to collect images of such objects (sunglasses etc.) and find appropriate locations to insert them in images. For example with sunglasses you would have to paste it in the right orientation, position and scale to cover the eyes. Therefore you would need the locations of the eyes, perhaps by performing facial keypoint localization or manual annotation. There are many ways to go about this.

Good luck with your work!

**Comment by adoniyas** [comment]
Thank you sir for your time, if there is anything you recommend me I would appreciate it.

**Comment by isarandi** [comment]
I'd suggest finding recent related work to see what is out there already and what datasets they use. There are many approaches for facial keypoint localization, so the question is pretty broad.
